# Generated by Django 4.2.2 on 2023-07-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_options_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='chat/profile_pics/default_profile_logo.png', upload_to='chat/profile_pics/'),
        ),
    ]
